[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"

[etherscan]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config